import type { Metadata } from "next";
import { fontVariables, defaultFontClassName } from "../design-system/fonts";
import "@/app/globals.css";
import { ReportWebVitals } from "@/components/web/ReportWebVitals";
import { UtmCapture } from "@/components/web/UtmCapture";
import { BoundaryProvider } from "@/components/internal/BoundaryProvider";
import Boundary from "@/components/internal/Boundary";
import BoundaryToggle from "@/components/internal/BoundaryToggle";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontVariables} ${defaultFontClassName} antialiased relative min-h-screen flex flex-col`}
            >
                <UtmCapture />
                <ReportWebVitals />
                <BoundaryProvider>
                    <Boundary rendering="static" hydration="server">
                        {children}
                        <BoundaryToggle />
                    </Boundary>
                </BoundaryProvider>
            </body>
        </html>
    );
}
